# Generated by Django 2.0.6 on 2018-06-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dungdung', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myform',
            options={'managed': True},
        ),
    ]
