# Generated by Django 2.0.6 on 2018-06-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dungdung', '0002_auto_20180627_1209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myform',
            new_name='form',
        ),
        migrations.AlterModelTable(
            name='form',
            table='form',
        ),
    ]
